apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../../base/apps/


namespace: dev

patches:
- target:
    kind: Deployment
    name: simple-deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/dshtranv/httpd-test-amd:latest