apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deployment
  name: simple-deployment
  namespace: to-change-by-kustomize
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-deployment
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/httpd-24:latest
        imagePullPolicy: Always
        name: simple-deployment
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault

        resources: {}