apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: simple-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080