apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/policies/

namespace: stage

patches:
- target:
    kind: Policy
    name: add-labels
  patch: |-
    - op: replace
      path: /spec/rules/0/mutate/patchStrategicMerge/metadata/labels/+(env)
      value: stage