apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd-route
  namespace: prod
  annotations:
    router.openshift.io/cookie_name: "cookie"
spec:
  #host: <CHANGE_ME>
  port:
    targetPort: 8080
  to:
    kind: Service
    name: httpd-service